version: 0.2

phases:
  build:
    commands:
      - echo "Building... Nothing to build for PHP. Just copying files."
  post_build:
    commands:
      - echo "Build completed."

artifacts:
  files:
    - '**/*'

